### PR TITLE
[Enhancement]: Add suppport for coqui xtts local text-to-speech

### PR DESCRIPTION
**Pull request by Paillat-dev**
## Proposed changes

Adding support for https://github.com/coqui-ai/TTS 's xtts-v2 model and its built-in voices.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) 💥
- [ ] Documentation Update (if none of the other choices apply) 📖

## Checklist

- [x] I have read the CONTRIBUTING.md 📚
- [ ] I have added tests that prove my fix is effective or that my feature works ✅✔️
- [x] I have added necessary documentation (if appropriate) 📝

### CODE REVIEW

**Comment by Paillat-dev** [comment]
Heyy @RayVentura I would love if you could review this &/ tell me if you are interested in it.

**Comment by RayVentura** [comment]
Hey, I'm currently reviewing your change. Adding CoquiTTS is really awesome, thanks a lot for the effort.

**Comment by RayVentura** [comment]
Hey, so I tried to run it locally on Docker, but the consent input from CoquiTTS prevents the automatic download of the model's weights. 
image
From looking at their code, they don't seem to provide an non-manual way of consenting to the download without typing in an actual input from the CLI:
image

On the first time the model gets downloaded:
image

**Comment by Paillat-dev** [comment]
Hmm that's correct. I must have not noticed that having already donwloaded it. I will add a script to run once to download it & some documentation. Thanks for testing

**Comment by Paillat-dev** [comment]
Here we go

**Comment by RayVentura** [comment]
Amazing, I'll check this within the next 24hours and merge if everything is fine. Thanks a lot. And don't hesitate to drop in, in the discord to coordinate on more stuff if you want.

**Comment by Paillat-dev** [comment]
Perfect. I am currently adding other features like credits management for audio & video assets and other things

**Pull request merged**
